spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/hubr
    username: geek
    password: geek
  liquibase:
    change-log: classpath:/liquibase/changelog.xml
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate.ddl-auto: validate
profile-uri: /profile
security-uri: /profile/security
mail-service:
  host: smtp.gmail.com
  port: 465
  login-mail: gbtestcase.mail@gmail.com
  password-mail: xchdibbwnhucijpe
  path-template: mail/template-mail
  display-from: hubr-gb
  base-url: http://localhost:8080
